### PR TITLE
Npsrts

### PR DESCRIPTION
**Pull request by MirijaHa**
closes issue: https://github.com/2DegreesInvesting/r2dii.climate.stress.test/issues/270

I nearly would have moved the filtering to the wrong spot, i.e. after dplyr::filter(!(scenario == "ETP2017_NPS" & ald_sector == "Power")). This would have meant that we would have gotten duplicate entries for some sectors and the workflow would have failed later on. I still think it is good if you look at this sharply once more @jacobvjk 

I also removed some outdated comment and added a simply check to avoid that in some weird situation NPS and NPSRTS are mixed.

### CODE REVIEW

**Review by cjyetman — APPROVED** [review]
lgtm.... if I understand correctly, it looks like this code will automatically adapt to either "NPS" or "NPSRTS", which I think is a very good idea 👍🏻

**Review by jacobvjk — CHANGES_REQUESTED** [review]
I think this may still be problematic, @MirijaHa because your check, which makes sense in principle, should fail if we have WEO2020_NPS and ETP2017_NPSRTS in the sample. This is likely going to be the case though. In the end this check would have to be run by scenario source

**Comment by jacobvjk** [comment]
OR we need to run this check by sector and use the scenario source/sector filtering from the user version.. which I guess is more complicated

**Comment by MirijaHa** [comment]
> I think this may still be problematic, @MirijaHa because your check, which makes sense in principle, should fail if we have WEO2020_NPS and ETP2017_NPSRTS in the sample. This is likely going to be the case though. In the end this check would have to be run by scenario source

I wonder if to simply remove this check, as actually based on the scenarioAnalysis files CJ provided it is actually impossible for NPS and NPSRTS to be in the same results, so it might be overly cautious to check this, what do you think?

**Comment by jacobvjk** [comment]
> > I think this may still be problematic, @MirijaHa because your check, which makes sense in principle, should fail if we have WEO2020_NPS and ETP2017_NPSRTS in the sample. This is likely going to be the case though. In the end this check would have to be run by scenario source
> 
> I wonder if to simply remove this check, as actually based on the scenarioAnalysis files CJ provided it is actually impossible for NPS and NPSRTS to be in the same results, so it might be overly cautious to check this, what do you think?

while we are at it, maybe it will pass with your test, as we seem to get WEO2019_SPS and then change that to WEO219_NPS later on after the NPSRTS check. But you will notice that this is really starting to get out of control slowly. We are also not handling WEO2020_SPS, if that should be required at some point. So I can approve this, but we should overhaul the handling of this not too far into the future

**Comment by jacobvjk** [comment]
we can also remove the check, you are right

**Review by jacobvjk — APPROVED** [review]
lgtm

**Pull request merged**
