### PR TITLE
add funding note

### PR DESCRIPTION
**Pull request by MirijaHa**
Combined formulation suggestion by Andy ```The developement of the stress-test methodology and the technical implementation as an R-tool was funded by the EU - LIFE PACTA 2.0 (LIFE19 GIC/DE/001294)``` with the formulation used in other r2dii packages. I am not so happy with the choice of the word tool, are u fine with it however @jacobvjk ?

### CODE REVIEW

**Comment by jacobvjk** [comment]
> Combined formulation suggestion by Andy `The developement of the stress-test methodology and the technical implementation as an R-tool was funded by the EU - LIFE PACTA 2.0 (LIFE19 GIC/DE/001294)` with the formulation used in other r2dii packages. I am not so happy with the choice of the word tool, are u fine with it however @jacobvjk ?

which other repo uses that formulation? Not seeing it here https://github.com/2DegreesInvesting/r2dii.analysis or here https://github.com/2DegreesInvesting/r2dii.match for example

**Comment by MirijaHa** [comment]
> > Combined formulation suggestion by Andy `The developement of the stress-test methodology and the technical implementation as an R-tool was funded by the EU - LIFE PACTA 2.0 (LIFE19 GIC/DE/001294)` with the formulation used in other r2dii packages. I am not so happy with the choice of the word tool, are u fine with it however @jacobvjk ?
> 
> which other repo uses that formulation? Not seeing it here https://github.com/2DegreesInvesting/r2dii.analysis or here https://github.com/2DegreesInvesting/r2dii.match for example

copy pasted from rdii.data, but also found the formulation in r2dii match ``` The views expressed are the sole responsibility of the authors and do not necessarily reflect the views of the funders. The funders are not responsible for any use that may be made of the information it contains.```

**Comment by jacobvjk** [comment]
> > > Combined formulation suggestion by Andy `The developement of the stress-test methodology and the technical implementation as an R-tool was funded by the EU - LIFE PACTA 2.0 (LIFE19 GIC/DE/001294)` with the formulation used in other r2dii packages. I am not so happy with the choice of the word tool, are u fine with it however @jacobvjk ?
> > 
> > 
> > which other repo uses that formulation? Not seeing it here https://github.com/2DegreesInvesting/r2dii.analysis or here https://github.com/2DegreesInvesting/r2dii.match for example
> 
> copy pasted from rdii.data, but also found the formulation in r2dii match ` The views expressed are the sole responsibility of the authors and do not necessarily reflect the views of the funders. The funders are not responsible for any use that may be made of the information it contains.`

Yes, I meant the use of the word R-tool. I thought that was what you are unhappy with? why not simply say something more generic such as `The development of the stress-test methodology and the technical software implementation was funded by the EU - LIFE PACTA 2.0 (LIFE19 GIC/DE/001294)`?

**Comment by MirijaHa** [comment]
> > > > Combined formulation suggestion by Andy `The developement of the stress-test methodology and the technical implementation as an R-tool was funded by the EU - LIFE PACTA 2.0 (LIFE19 GIC/DE/001294)` with the formulation used in other r2dii packages. I am not so happy with the choice of the word tool, are u fine with it however @jacobvjk ?
> > > 
> > > 
> > > which other repo uses that formulation? Not seeing it here https://github.com/2DegreesInvesting/r2dii.analysis or here https://github.com/2DegreesInvesting/r2dii.match for example
> > 
> > 
> > copy pasted from rdii.data, but also found the formulation in r2dii match ` The views expressed are the sole responsibility of the authors and do not necessarily reflect the views of the funders. The funders are not responsible for any use that may be made of the information it contains.`
> 
> Yes, I meant the use of the word R-tool. I thought that was what you are unhappy with? why not simply say something more generic such as `The development of the stress-test methodology and the technical software implementation was funded by the EU - LIFE PACTA 2.0 (LIFE19 GIC/DE/001294)`?

thats what I was looking for, adapting

**Review by jacobvjk — APPROVED** [review]
lgtm

**Pull request merged**
