### PR TITLE
use exposure from last year of prod forecast

### PR DESCRIPTION
**Pull request by jacobvjk**
preparation for tmsr/smsp fix

This PR:
- uses the last year of the production forecast to derive company/technology level exposures.
- any company for which the production share within their ald_sector changes over that time frame will have a different overall loss. However the percentage change on company_technology level should remain the same

### CODE REVIEW

**Review by MirijaHa — COMMENTED** [review]
Before i approve, did you verify that your expectations hold true?

**Comment by jacobvjk** [comment]
additional expectation: companies that fade out production over the 5 year horizon will be kicked out

**Comment by jacobvjk** [comment]
tested assumption:
- with toy data company 115 (all exposures stay stable) nothing changes, for other toy data companies with changes in production composition, the losses change.
- both companies (107 and 114) which fade out a technology (no matter if high or low carbon, have this technology removed)
- the relative magnitude of the shocks remains unchanged

**Review by MirijaHa — APPROVED** [review]
yolo

**Pull request merged**
