### PR TITLE
report only problematic cases

### PR DESCRIPTION
**Pull request by MirijaHa**
Experimental change to make missings more salient.

### CODE REVIEW

**Comment by MirijaHa** [comment]
Suggestion to close https://dev.azure.com/2DegreesInvesting/2DegreesInvesting/_boards/board/t/Stress%20Testing%20Developers/Backlog%20items/?workitem=4120

Now:

- all input data check throw errors
- missings are printed to the screen in a less cluttery way.

What you can see, is that there are still NAs on 4 columns for equity and loans, example ```Counted 16635 missings on column production_plan_company_technology 
Counted 1109 missings on column production_change_target_scenario 
Counted 42 missings on column net_profits_shock_scenario 
Counted 42 missings on column discounted_net_profits_shock_scenario ```

**Comment by jacobvjk** [comment]
I would prefer to investigate the remaining issues on the linked ADO ticket

**Comment by MirijaHa** [comment]
@jacobvjk  I hate to say this but also after your fix the loans workflow still reports: ```Reporting missings on dataset: Company Trajectories 
Counted 19725 missings on column production_plan_company_technology 
Counted 1315 missings on column production_change_target_scenario 
Counted 210 missings on column net_profits_shock_scenario 
Counted 210 missings on column discounted_net_profits_shock_scenario ```

**Review by jacobvjk — APPROVED** [review]
lgtm

**Pull request merged**
