### PR TITLE
Move non-standard files to inst/ns

### LINKED ISSUE #122: Enable using the package in user-mode
Right now the package lacks access to required files.

It works on devleoper mode because the project can
reach the source code under its root.

``` r
devtools::load_all()
#> ℹ Loading r2dii.climate.stress.test
packageVersion("r2dii.climate.stress.test")
#> [1] '0.0.0.9000'

here::here()
#> [1] "/home/mauro/git/r2dii.climate.stress.test"

x <- capture.output( # Suppress printed output
  run_stress_test_bonds()
)
#> Warning in filter_negative_late_and_sudden(data): Removed 21 rows because negative production compensation targets were set in late and sudden.
#>                    Negative absolute production is impossible
```

It fails on user-mode because non-standard files like
"./stress_test_model_functions.R" are not installed.

``` r
library(r2dii.climate.stress.test)
packageVersion("r2dii.climate.stress.test")
#> [1] '0.0.0.9000'

here::here()
#> [1] "/tmp/Rtmpps4U2j/reprex-13fe2228c38d7-super-sable"

x <- capture.output( # Suppress printed output
  run_stress_test_bonds()
)
#> Warning in file(filename, "r", encoding = encoding): cannot open file
#> 'stress_test_model_functions.R': No such file or directory
#> Error in file(filename, "r", encoding = encoding): cannot open the connection
```

While we decide what to do with non-standard files, I think we should move or copy
them to inst/ so they do install and we can use the package in user-mode, e.g.
to show examples in README or vignettes/.

### PR DESCRIPTION
**Pull request by maurolepore**
Closes #122 

This PR moves non-standard files from the root to inst/ns (install non-standard). This is a way to 
ensure the required but non-standard files are installed in the user's system. 

Benefits:

1. The user no longer needs to clone the source repo. 
2. The package a lil closer to meeting CRAN policies.
3. We can now write an integration test in the form of an article or examples in README, Get started, or other articles (see #125).

The trick is based on the following:
 
* Move files to inst/ns
* Redirect paths to inst/ns in `source_all()` and in `get_config()` -- a thin wrapper around `config::get()`.

### CODE REVIEW

**Review by MirijaHa — COMMENTED** [review]
I had decided against doing this for now since:

- this changes the absolute path to web_tool_(external)_stress_tests change, and since I do not know how those scripts are called from transition monitor I am not sure if this will cause a problem
- I would prefer to immediately put the files that where in the root dir to their final destiny, which for most files would be deletion, and for one file the R dir., for a few files the inst folder

Thus let us quickly talk about this in the prio synch later before merging this.

**Comment by jacobvjk** [comment]
@maurolepore @MirijaHa this will almost certainly need an adjustment on the PACTA_analysis side so that the stress test still gets called correctly in the web tool. Please check this before merging!

**Comment by maurolepore** [comment]
@MirijaHa and @jacobvjk thanks for noticing the negative consequences of merging this. To lower the risk I changed this PR to a draft.

I see two ways to win-win approaches -- to avoid braking changes AND meet the structural requirements of an R package:

1. Copy (not move) the root files to inst/. The copy at the root will keep any dependency working, while the copy in inst/ will help the package behave as such.


2. Extract the package and call it. The package could move to say 2DegreesInvesting/st.climate then in this repo we could use it with `library(st.climate)`. The root would remain as is; everything package related could be removed -- i.e. DESCRIPTION, R/, tests/, etc.

**Comment by maurolepore** [comment]
I'm closing because @MirijaHa plans a different approach. 

For the record, the problem this PR solves is demonstrated by this reprex:

This code

```r
reprex::reprex({
  library(r2dii.climate.stress.test)
  run_stress_test_bonds()
})
```

yields this output:

``` r
library(r2dii.climate.stress.test)
run_stress_test_bonds()
#> Warning in file(filename, "r", encoding = encoding): cannot open file
#> 'stress_test_model_functions.R': No such file or directory
#> Error in file(filename, "r", encoding = encoding): cannot open the connection
```

Note you won't get an error if instead you use the package in developer mode:

This code 

```r
reprex::reprex(wd = ".", {
  devtools::load_all()
  run_stress_test_bonds()
})
```

yields this output

``` r
devtools::load_all()
#> ℹ Loading r2dii.climate.stress.test
run_stress_test_bonds()
#> Warning in filter_negative_late_and_sudden(data): Removed 21 rows because negative production compensation targets were set in late and sudden.
#>                    Negative absolute production is impossible
#> When joining annual profits on financial data on columns company_name corporate_bond_ticker ald_sector technology dropped 2877 rows from annual profits .
#> When joining plan carsten on financial data on columns company_name corporate_bond_ticker ald_sector technology dropped 137 rows from plan carsten .
#> Reporting missings on dataset: Stress test results - Company level 
#> Counted 0 missings on column investor_name 
#> Counted 0 missings on column portfolio_name 
#> Counted 0 missings on column company_name 
#> Counted 0 missings on column scenario_geography 
#> Counted 0 missings on column scenario_name 
#> Counted 0 missings on column year_of_shock 
#> Counted 0 missings on column duration_of_shock 
#> Counted 0 missings on column ald_sector 
#> Counted 0 missings on column technology 
#> Counted 515 missings on column production_shock_perc 
#> Counted 0 missings on column asset_portfolio_value 
#> Counted 0 missings on column tech_company_exposure 
#> Counted 0 missings on column VaR_tech_company 
#> Counted 0 missings on column tech_company_value_change 
#> Counted 0 missings on column company_exposure 
#> Counted 13 missings on column VaR_company 
#> Counted 13 missings on column company_value_change 
#> Counted 0 missings on column technology_exposure 
#> Counted 0 missings on column VaR_technology 
#> Counted 0 missings on column technology_value_change 
#> Counted 0 missings on column sector_exposure 
#> Counted 0 missings on column VaR_sector 
#> Counted 0 missings on column sector_value_change 
#> Counted 0 missings on column analysed_sectors_exposure 
#> Counted 0 missings on column VaR_analysed_sectors 
#> Counted 0 missings on column analysed_sectors_value_change 
#> Counted 0 missings on column portfolio_aum 
#> Counted 0 missings on column portfolio_value_change_perc 
#> Counted 0 missings on column portfolio_value_change 
#> Counted 0 missings on column exclude 
#> 
#> 
#> Reporting missings on dataset: Stress test results - Portfolio level 
#> Counted 0 missings on column investor_name 
#> Counted 0 missings on column portfolio_name 
#> Counted 0 missings on column scenario_geography 
#> Counted 0 missings on column scenario_name 
#> Counted 0 missings on column year_of_shock 
#> Counted 0 missings on column duration_of_shock 
#> Counted 0 missings on column ald_sector 
#> Counted 0 missings on column technology 
#> Counted 12 missings on column production_shock_perc 
#> Counted 0 missings on column asset_portfolio_value 
#> Counted 0 missings on column technology_exposure 
#> Counted 0 missings on column VaR_technology 
#> Counted 0 missings on column technology_value_change 
#> Counted 0 missings on column sector_exposure 
#> Counted 0 missings on column VaR_sector 
#> Counted 0 missings on column sector_value_change 
#> Counted 0 missings on column analysed_sectors_exposure 
#> Counted 0 missings on column VaR_analysed_sectors 
#> Counted 0 missings on column analysed_sectors_value_change 
#> Counted 0 missings on column portfolio_aum 
#> Counted 0 missings on column portfolio_value_change_perc 
#> Counted 0 missings on column portfolio_value_change 
#> 
#> 
#> Reporting missings on dataset: Expected loss 
#> Counted 0 missings on column scenario_name 
#> Counted 0 missings on column scenario_geography 
#> Counted 0 missings on column investor_name 
#> Counted 0 missings on column portfolio_name 
#> Counted 0 missings on column company_name 
#> Counted 0 missings on column id 
#> Counted 0 missings on column ald_sector 
#> Counted 0 missings on column equity_0_baseline 
#> Counted 0 missings on column equity_0_late_sudden 
#> Counted 0 missings on column debt 
#> Counted 0 missings on column volatility 
#> Counted 0 missings on column risk_free_rate 
#> Counted 0 missings on column term 
#> Counted 0 missings on column Survival_baseline 
#> Counted 0 missings on column Survival_late_sudden 
#> Counted 0 missings on column PD_baseline 
#> Counted 0 missings on column PD_late_sudden 
#> Counted 0 missings on column PD_change 
#> Counted 0 missings on column pd 
#> Counted 0 missings on column lgd 
#> Counted 0 missings on column percent_exposure 
#> Counted 0 missings on column exposure_at_default 
#> Counted 0 missings on column expected_loss_baseline 
#> Counted 0 missings on column expected_loss_late_sudden 
#> 
#> 
#> Reporting missings on dataset: Annual PD changes sector 
#> Counted 0 missings on column scenario_name 
#> Counted 0 missings on column scenario_geography 
#> Counted 0 missings on column investor_name 
#> Counted 0 missings on column portfolio_name 
#> Counted 0 missings on column ald_sector 
#> Counted 0 missings on column year 
#> Counted 0 missings on column PD_change 
#> 
#> 
#> Reporting missings on dataset: Overall PD changes sector 
#> Counted 0 missings on column scenario_name 
#> Counted 0 missings on column scenario_geography 
#> Counted 0 missings on column investor_name 
#> Counted 0 missings on column portfolio_name 
#> Counted 0 missings on column ald_sector 
#> Counted 0 missings on column term 
#> Counted 0 missings on column PD_change
```

<sup>Created on 2021-11-01 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Pull request closed without merging**
