### PR TITLE
Streamlining

### PR DESCRIPTION
**Pull request by MirijaHa**
In this PR I merely copy pasted all processings and check that are done into 1 function per dataset. This way it is easier to see current unneeded steps and inconsistencies
Snapshot tests pass.

Remaining steps in this endeavour:

- remove all inconssitencies and superfluous information
- take import, and if possible wrangling, out of the loop

### CODE REVIEW

**Review by jacobvjk — COMMENTED** [review]
integration check with web tool successful?

**Comment by MirijaHa** [comment]
> integration check with web tool successful?

it wasnt at first, but the intergation check found an issues which I then fixed 🤓

**Comment by jacobvjk** [comment]
> > integration check with web tool successful?
> 
> it wasnt at first, but the intergation check found an issues which I then fixed 🤓

amazing

**Review by jacobvjk — APPROVED** [review]
lgtm

**Pull request merged**
