### PR TITLE
No sourcing from user flows

### PR DESCRIPTION
**Pull request by MirijaHa**
This PR closes 2557.

All Change checks passed.
```
library(r2dii.climate.stress.test)
 run_stress_test(<asset_type>)
```
could be run without problems.

NOTE in order to be able to run_stress_test from another dir than the package dir I had to get rid of a using a config file in user workflow. I was going to do that anyway so see no problem there. 

Except for that:

- i left webtool related things untouched as far a possible
- i deleted a superfluous config file
- i move QA and research to designated subdirs in inst.
- 
One question @maurolepore I removed the files that where moved to isnt from buildignore. Given they are in inst now, which is moved up one level upon installation (https://r-pkgs.org/inst.html), am I right in thinking that the files will now be included in the users installation whereas before they were not?

### CODE REVIEW

**Review by jacobvjk — APPROVED** [review]
lgtm

**Comment by maurolepore** [comment]
@MirijaHa, correct. Here is what I see after checking out this PR locally and intalling the package:



``` r
library(r2dii.climate.stress.test)
fs::dir_tree(system.file(package = "r2dii.climate.stress.test"))
#> /home/mauro/R/x86_64-pc-linux-gnu-library/4.1/r2dii.climate.stress.test
#> ├── DESCRIPTION
#> ├── INDEX
#> ├── LICENSE
#> ├── Meta
#> │   ├── Rd.rds
#> │   ├── features.rds
#> │   ├── hsearch.rds
#> │   ├── links.rds
#> │   ├── nsInfo.rds
#> │   └── package.rds
#> ├── NAMESPACE
#> ├── QA_scripts
#> │   ├── change_check_cb.R
#> │   ├── change_check_cl.R
#> │   ├── change_check_eq.R
#> │   ├── qa_cb.R
#> │   ├── qa_cl.R
#> │   ├── qa_eq.R
#> │   └── wip_data_qa.R
#> ├── R
#> │   ├── r2dii.climate.stress.test
#> │   ├── r2dii.climate.stress.test.rdb
#> │   └── r2dii.climate.stress.test.rdx
#> ├── help
#> │   ├── AnIndex
#> │   ├── aliases.rds
#> │   ├── figures
#> │   │   └── README-pressure-1.png
#> │   ├── paths.rds
#> │   ├── r2dii.climate.stress.test.rdb
#> │   └── r2dii.climate.stress.test.rdx
#> ├── html
#> │   ├── 00Index.html
#> │   └── R.css
#> └── research
#>     ├── params_litigation_risk.yml
#>     └── stress_test_litigation_risk.R
```

<sup>Created on 2021-11-02 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by MirijaHa** [comment]
> @MirijaHa, correct. Here is what I see after checking out this PR locally and intalling the package:
> 
> ```r
> library(r2dii.climate.stress.test)
> fs::dir_tree(system.file(package = "r2dii.climate.stress.test"))
> #> /home/mauro/R/x86_64-pc-linux-gnu-library/4.1/r2dii.climate.stress.test
> #> ├── DESCRIPTION
> #> ├── INDEX
> #> ├── LICENSE
> #> ├── Meta
> #> │   ├── Rd.rds
> #> │   ├── features.rds
> #> │   ├── hsearch.rds
> #> │   ├── links.rds
> #> │   ├── nsInfo.rds
> #> │   └── package.rds
> #> ├── NAMESPACE
> #> ├── QA_scripts
> #> │   ├── change_check_cb.R
> #> │   ├── change_check_cl.R
> #> │   ├── change_check_eq.R
> #> │   ├── qa_cb.R
> #> │   ├── qa_cl.R
> #> │   ├── qa_eq.R
> #> │   └── wip_data_qa.R
> #> ├── R
> #> │   ├── r2dii.climate.stress.test
> #> │   ├── r2dii.climate.stress.test.rdb
> #> │   └── r2dii.climate.stress.test.rdx
> #> ├── help
> #> │   ├── AnIndex
> #> │   ├── aliases.rds
> #> │   ├── figures
> #> │   │   └── README-pressure-1.png
> #> │   ├── paths.rds
> #> │   ├── r2dii.climate.stress.test.rdb
> #> │   └── r2dii.climate.stress.test.rdx
> #> ├── html
> #> │   ├── 00Index.html
> #> │   └── R.css
> #> └── research
> #>     ├── params_litigation_risk.yml
> #>     └── stress_test_litigation_risk.R
> ```
> 
> Created on 2021-11-02 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)

Mh, to that background I wonder if moving them back to root level and build ignoring them would not be the preferable option, after all the files are of no use to the end user. Does there happen to be another storage folder (attic or alike) to store non standard files that shall be exclued from build?

**Review by maurolepore — APPROVED** [review]
LGTM -- I see checks passing green.

**Comment by maurolepore** [comment]
@MirijaHa, I agree. If users don't need those files it's better to exclude them from inst/. Those files will increase the installation size, and therefore the time the package take to install. Also past some limit CRAN rejects packages solely due to size.

I know of no standard non-standard directory :-). In a PR that didn't fly I used "ns/" as the short form of non-standard. In my case I used the directory "./inst/ns/" but you may as well use "./ns" and add "ns/" to .Rbuildignore.

(Or -- you could extract the package to another repo and use it in here with `library()` -- so this repo remains a the legacy, unstructured grab-bag and the package lives elsewhere in its neat house :smile: )

**Comment by MirijaHa** [comment]
> @MirijaHa, I agree. If users don't need those files it's better to exclude them from inst/. Those files will increase the installation size, and therefore the time the package take to install. Also past some limit CRAN rejects packages solely due to size.
> 
> I know of no standard non-standard directory :-). In a PR that didn't fly I used "ns/" as the short form of non-standard. In my case I used the directory "./inst/ns/" but you may as well use "./ns" and add "ns/" to .Rbuildignore.
> 
> (Or -- you could extract the package to another repo and use it in here with `library()` -- so this repo remains a the legacy, unstructured grab-bag and the package lives elsewhere in its neat house 😄 )

will use buildignored dir nonstandard for now, let us lay the foundation for buring the unstructured grab bag in two weeks then :)

**Pull request merged**
