### PR TITLE
Ado 4121

### PR DESCRIPTION
**Pull request by MirijaHa**
changed loanbook prep to return all geos and to use custom formatting of SenarioAnalysisInput data. 
These changes do not affect the results as calculated for level global. 
Please not however that not all geos as identified here: https://github.com/2DegreesInvesting/r2dii.stress.test.data/blob/898f30a0b80d837ba59c88665c998b503eaf2d67/data_overview/scenario_x_scenario_geography_availability.R#L422 are included. Included are ```[1] "Global"                 "AdvancedEconomies"      "Africa"                 "AsiaPacific"            "CentralandSouthAmerica" "DevelopingEconomies"   
 [7] "Eurasia"                "Europe"                 "EU"                     "MiddleEast"             "NonOECD"                "NorthAmerica"          
[13] "OECD"                   "China"                  "SoutheastAsia"  ```

### CODE REVIEW

**Review by jacobvjk — COMMENTED** [review]
do we know why we do not get results for all geos? anything systematic or simply due to loan book structure?

**Comment by MirijaHa** [comment]
> do we know why we do not get results for all geos? anything systematic or simply due to loan book structure?

I had a bit of hope that with your superior widmo you can make an educated guess, if not I will look into it in detail.

**Comment by MirijaHa** [comment]
> > do we know why we do not get results for all geos? anything systematic or simply due to loan book structure?
> 
> I had a bit of hope that with your superior widmo you can make an educated guess, if not I will look into it in detail.

@jacobvjk , this is where we lose many geos, does that make sense to you? https://github.com/2DegreesInvesting/r2dii.climate.stress.test/blob/e3f4fa333371fb56dca652f156bc56d5682c1c7f/R/format_loanbook_st.R#L110

**Review by jacobvjk — APPROVED** [review]
lgtm

**Pull request merged**
